const axios = require("axios")
const tough = require("tough-cookie")
const axiosCookieJarSupport = require("axios-cookiejar-support").default

axiosCookieJarSupport(axios)

const cookieJar = new tough.CookieJar()
axios.defaults.jar = cookieJar
axios.defaults.withCredentials = true

const BASE_URL = "https://www.khanacademy.org"
const loginUrl = `${BASE_URL}/login`

exports.KhanApi = class {
  authenticated = false
  authenticate = async (identifier, password) =>
    axios({
      url: loginUrl,
      method: "post",
      data: `identifier=${encodeURIComponent(
        identifier
      )}&password=${encodeURIComponent(password)}`,
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
    }).then((res) => {
      if (res.data.error) {
        throw new Error(res.data.error)
      }
      this.authenticated = true
      return true
    })

  // helper methods to wrap axios
  axios() {
    return axios(...arguments)
  }
  get() {
    return axios.get(...arguments)
  }
  post() {
    return axios.post(...arguments)
  }

  // helper method to wrap calls to graphQL
  graphQL = async (endpoint, payload, method = "POST") => {
    let url = `${BASE_URL}/api/internal/graphql${endpoint}`
    return method === "POST" ? this.post(url, payload) : this.get(url, payload)
  }

  /*************** ADD AND MAINTAIN METHODS BELOW *****************************/
  /* Discover methods by looking at the network tab in devtools when visiting a
   * page in Khan Academy. Add the payload values as an object, and then you can
   * fetch the data using this.graphQL
   */

  getCoach = async () => {
    let payload = {
      operationName: "getCoach",
      query:
        "query getCoach {\n  coach {\n    id\n    nickname\n    __typename\n  }\n  countries {\n    id\n    code\n    translatedName\n    __typename\n  }\n  user {\n    id\n    tosForFormalTeacherStatus\n    schoolAffiliation {\n      id\n      name\n      postalCode\n      location\n      __typename\n    }\n    affiliationCountryCode\n    __typename\n  }\n}\n",
      variables: {},
    }
    return this.graphQL("/getCoach", payload)
  }

  ProgressByStudent = async (classId, pageSize = 1000) => {
    let payload = {
      operationName: "ProgressByStudent",
      variables: {
        classId,
        pageSize,
        assignmentFilters: { dueAfter: null, dueBefore: null },
        contentKinds: null,
        after: null,
      },
      query:
        "query ProgressByStudent($assignmentFilters: CoachAssignmentFilters, $contentKinds: [LearnableContentKind], $classId: String!, $pageSize: Int, $after: ID) {\n  coach {\n    id\n    studentList(id: $classId) {\n      id\n      cacheId\n      studentKaidsAndNicknames {\n        id\n        coachNickname\n        __typename\n      }\n      assignmentsPage(filters: $assignmentFilters, after: $after, pageSize: $pageSize) {\n        assignments(contentKinds: $contentKinds) {\n          id\n          dueDate\n          contents {\n            id\n            translatedTitle\n            kind\n            defaultUrlPath\n            __typename\n          }\n          itemCompletionStates: itemCompletionStatesForAllStudents {\n            completedOn\n            studentKaid\n            bestScore {\n              numAttempted\n              numCorrect\n              __typename\n            }\n            __typename\n          }\n          __typename\n        }\n        pageInfo {\n          nextCursor\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n",
    }

    return this.graphQL("/ProgressByStudent", payload)
  }

  getStudentsList = async ({ classId = "", pageSize = 40 }) => {
    let payload = {
      operationName: "getStudentsList",
      variables: { hasClassId: !!classId, classId, after: 0, pageSize },
      query:
        "query getStudentsList($hasClassId: Boolean!, $classId: String!, $after: Int, $pageSize: Int) {\n  coach {\n    id\n    countStudents @skip(if: $hasClassId)\n    studentsPage(after: $after, pageSize: $pageSize) @skip(if: $hasClassId) {\n      ...StudentField\n      __typename\n    }\n    invitations @skip(if: $hasClassId) {\n      ...InvitationsField\n      __typename\n    }\n    coachRequests @skip(if: $hasClassId) {\n      ...CoachRequestField\n      __typename\n    }\n    studentLists: coachedStudentLists {\n      id\n      cacheId\n      name\n      topicTitle\n      key\n      studentKaids @skip(if: $hasClassId)\n      isDistrictSynced\n      __typename\n    }\n    studentList(id: $classId) @include(if: $hasClassId) {\n      id\n      cacheId\n      name\n      key\n      autoGenerated\n      signupCode\n      topics {\n        id\n        key\n        iconPath\n        __typename\n      }\n      countStudents\n      studentsPage(after: $after, pageSize: $pageSize) {\n        ...StudentField\n        __typename\n      }\n      invitations {\n        ...InvitationsField\n        __typename\n      }\n      coachRequests {\n        ...CoachRequestField\n        __typename\n      }\n      isDistrictSynced\n      __typename\n    }\n    schoolAffiliation {\n      id\n      __typename\n    }\n    affiliationCountryCode\n    __typename\n  }\n  user {\n    id\n    tosForFormalTeacherStatus\n    __typename\n  }\n}\n\nfragment CoachRequestField on CoachRequest {\n  id\n  email: studentIdentifier\n  __typename\n}\n\nfragment InvitationsField on Invitation {\n  id\n  email\n  accepted\n  __typename\n}\n\nfragment StudentField on StudentsPage {\n  students {\n    kaid\n    id\n    email\n    coachNickname\n    profileRoot\n    username\n    __typename\n  }\n  nextCursor\n  __typename\n}\n",
    }

    return this.graphQL("/getStudentsList", payload)
  }

  ClassSubjectMasteryProgress = async ({ classId, topicId }) => {
    let payload = {
      operationName: "ClassSubjectMasteryProgress",
      variables: { classId, topicId },
      query:
        "query ClassSubjectMasteryProgress($classId: String!, $topicId: String!) {\n  topicById(id: $topicId) {\n    id\n    childTopics {\n      id\n      translatedTitle\n      __typename\n    }\n    __typename\n  }\n  coach {\n    id\n    studentList(id: $classId) {\n      id\n      cacheId\n      students {\n        id\n        coachNickname\n        subjectProgress(topicId: $topicId) {\n          currentMastery {\n            percentage\n            pointsEarned\n            pointsAvailable\n            __typename\n          }\n          unitProgresses {\n            topic {\n              id\n              __typename\n            }\n            currentMastery {\n              percentage\n              pointsEarned\n              pointsAvailable\n              __typename\n            }\n            __typename\n          }\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n",
    }

    return this.graphQL("/ClassSubjectMasteryProgress", payload)
  }

  getFullUserProfile = async () => {
    let payload = {
      operationName: "getFullUserProfile",
      variables: {},
      query:
        'query getFullUserProfile($kaid: String, $username: String) {\n  user(kaid: $kaid, username: $username) {\n    id\n    kaid\n    key\n    userId\n    email\n    username\n    userLanguage\n    profileRoot\n    childPageRoot\n    gaUserId\n    qualarooId\n    isPhantom\n    isDeveloper: hasRole(name: "admin")\n    isCurator: hasRole(name: "curator", scope: ANY_ON_CURRENT_LOCALE)\n    isCreator: hasRole(name: "creator", scope: ANY_ON_CURRENT_LOCALE)\n    isPublisher: hasPermission(name: "can_publish", scope: ANY_ON_CURRENT_LOCALE)\n    isModerator: hasPermission(name: "can_moderate_users", scope: GLOBAL)\n    isPublic\n    isParent\n    isTeacher\n    isDataCollectible\n    isChild\n    isOrphan\n    isActivityAccessible\n    isCoachingLoggedInUser\n    isParentOfLoggedInUser\n    canModifyCoaches\n    nickname\n    hideVisual\n    joined\n    points\n    countVideosCompleted\n    publicBadges {\n      badgeCategory\n      description\n      isOwned\n      isRetired\n      name\n      points\n      absoluteUrl\n      hideContext\n      icons {\n        smallUrl\n        compactUrl\n        emailUrl\n        largeUrl\n        __typename\n      }\n      relativeUrl\n      safeExtendedDescription\n      slug\n      translatedDescription\n      translatedSafeExtendedDescription\n      __typename\n    }\n    bio\n    background {\n      name\n      imageSrc\n      __typename\n    }\n    schoolAffiliation {\n      id\n      name\n      postalCode\n      location\n      __typename\n    }\n    affiliationCountryCode\n    soundOn\n    muteVideos\n    prefersReducedMotion\n    noColorInVideos\n    autocontinueOn\n    avatar {\n      name\n      imageSrc\n      __typename\n    }\n    hasChangedAvatar\n    newNotificationCount\n    canHellban: hasPermission(name: "can_ban_users", scope: GLOBAL)\n    canMessageUsers: hasPermission(name: "can_send_moderator_messages", scope: GLOBAL)\n    canCreateOfficialClarifications: hasPermission(name: "can_approve_clarifications", scope: GLOBAL)\n    canEvalCsProjects\n    discussionBanned\n    isSelf: isActor\n    hasStudents\n    hasClasses\n    hasChildren\n    hasCoach\n    badgeCounts\n    homepageUrl\n    hasCoachHomepage\n    hasParentHomepage\n    isMidsignupPhantom\n    streakLastExtended\n    streakLastLength\n    includesDistrictOwnedData\n    preferredKaLocale {\n      id\n      kaLocale\n      status\n      __typename\n    }\n    __typename\n  }\n}\n',
    }

    return this.graphQL("/getFullUserProfile", payload)
  }
}
